const listeUsers =  [
    {
      nom: "Anis",
      prenom: "Allagui",
      dateNaissance: "2002-04-14",
      age: "19",
      poste: "Stagiaire",
      salaire: 1000,
   
    },
    {
      nom: "saif",
      prenom: "abbes",
      dateNaissance: "1989-05-12",
      age: "33",
      poste: "responsable matriel",
      salaire: 900,
    },
    {
      nom: "nidhal",
      prenom: "yousfi",
      dateNaissance: "1991-05-10" ,
      age: "31",
      poste: "devloppeur web",
      salaire: 2500,
    },
    {
        nom: "asma",
        prenom: "selmi",
        dateNaissance: "1989-08-10",
        age: "33",
        poste: "ingeinieur AI",
        salaire: 2000,
      },
      {
        nom: "sirine",
        prenom: "mlouk",
        dateNaissance: "1997-03-02",
        age: "25",
        poste: "devloppeur web",
        salaire: 2300,
      },
      {
        nom: "rihem",
        prenom: "alaya",
        dateNaissance: "1981-04-02",
        age: "39",
        poste: "devloppeur web",
        salaire: 3700,
      },
      {
        nom: "raouf",
        prenom: "melki",
        dateNaissance: "1999-02-12",
        age: "23",
        poste: "devloppeur web",
        salaire: 1.900,
      },
      {
        nom: "nidhal",
        prenom: "yousfi",
        dateNaissance: "1991-02-12",
        age: "31",
        poste: "devloppeur web",
        salaire: 2500,
      },
      {
        nom: "Azer",
        prenom: "ghanem",
        dateNaissance: "2001-04-05",
        age: "20",
        poste: "DGA",
        salaire: 5000,
      },
      {
        nom: "Amina",
        prenom: "makhloufi",
        dateNaissance: "1995-05-09",
        age: "27",
        poste: "ingénieur Big Data",
        salaire: 2100 ,
      },
      {
        nom: "ahmed",
        prenom: "ahmed",
        dateNaissance: "1996-05-10",
        age: "28",
        poste: "chaufeur",
        salaire: 1000,
      },
      {
        nom: "olfa",
        prenom: "mahrzi",
        dateNaissance: "1992-12-08",
        age: "30",
        poste: "designer",
        salaire: 1700,
      },
      {
        nom: "eya",
        prenom: "jouini",
        dateNaissance: "1988-08-03",
        age: "34",
        poste: "marketing",
        salaire: 1800 ,
      },
      {
        nom: "amine",
        prenom: "maayoufi",
        dateNaissance: "2000-08-08",
        age: "23",
        poste: "organisateur",
        salaire: 2000,
      },
      {
        nom: "fedi",
        prenom: "khalil",
        dateNaissance: "1999-05-03",
        age: "23",
        poste: "devloppeur",
        salaire: 1700,
      },
  ]
export { listeUsers }